### PR TITLE
#156185242 #156185411 Unit test and Update ReadME File

### PR DESCRIPTION
**Pull request by tomuhenry**
**What does this PR do?**
- This PR completes the tasks to write unit tests and update ReadMe file

**Description of Task to be completed? **
- Update readMe file with demo gif
- Write a unit test for GitHub service class

**Relevant Pivotal Tracker Stories**
[#156185411](https://www.pivotaltracker.com/story/show/156185411)
[#156185242](https://www.pivotaltracker.com/story/show/156185242)

### CODE REVIEW

**Comment by tomuhenry** [comment]
@bibangamba, could you review this PR when you get some time

**Review by bibangamba — CHANGES_REQUESTED** [review]
Good work on the unit test @tomuhenry. Please improve your README to indicate how your project can be set up, as well as other characteristics or design choices. [This] sample README doc was shared on the PT story. Try emulating it. You might not need to include every section, but ensure to include the ones that you have material for.

**Review by bibangamba — APPROVED** [review]
this LGTM

**Comment by tomuhenry** [comment]
@bibangamba can it be merged whenever?

**Pull request merged**
